services:
  nginx:
    image: nginx:latest
    container_name: unicon_nginx_container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - drf 
      - redis
    networks:
      - app-network

  drf:
    build: .
    container_name: unicon_drf_backend_container
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: unicon_redis_container
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge