services:

  drf:
    build: .
    container_name: unicon_drf_backend_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "587:587"
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: unicon_postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: unicon
    ports:
      - "5432:5432"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: unicon_redis_container
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge