services:
  nginx:
    image: nginx:latest
    container_name: unicon_nginx_container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ../frontend/dist:/dist
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - drf 
      - redis
    networks:
      - app-network

  drf:
    build: .
    container_name: unicon_drf_backend_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: unicon_postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: unicon
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: unicon_redis_container
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge