services:
  drf:
    build: .
    container_name: unicon_drf_backend_container
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - drf 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge