FROM python:3.12-slim

# Force the python to output everything
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends gcc libpq-dev \
 && rm -rf /var/lib/apt/lists/*

# Prevent pip caching to save some space
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

COPY . .

# DRF port
EXPOSE 8000

CMD ["gunicorn", "src.src.wsgi:application", \
      "--bind", "0.0.0.0:8000", \
      "--workers", "1",           \
      "--threads", "2",           \
      "--worker-class", "gthread",\
      "--worker-tmp-dir", "/dev/shm"]