# Generated by Django 5.0.4 on 2024-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="email_identifier",
            field=models.CharField(default="unknown", max_length=10),
        ),
    ]
