# Generated by Django 5.0.4 on 2025-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_school_email_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gmail",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
