# Generated by Django 5.0.4 on 2025-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_gmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
