# Generated by Django 5.0.4 on 2025-07-21 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_user_validation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_notification_check",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
