# Generated by Django 5.0.4 on 2025-07-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_last_notification_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications_threshold",
            field=models.IntegerField(default=5),
        ),
    ]
