# Generated by Django 5.0.4 on 2025-07-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="validation_code",
        ),
    ]
