# Generated by Django 5.0.4 on 2024-08-27 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_article_user_temp_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_static_points',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_temp_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_temp_names',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_static_points',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_temp_name',
        ),
        migrations.CreateModel(
            name='ArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_temp_name', models.CharField(default='unknown', max_length=100)),
                ('user_static_points', models.BigIntegerField(default=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
