# Generated by Django 5.0.4 on 2024-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_remove_articletag_article_remove_articletag_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
