# Generated by Django 5.0.4 on 2025-03-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email",
            field=models.BooleanField(default=False),
        ),
    ]
