# Generated by Django 5.0.4 on 2024-12-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
