# Generated by Django 5.0.4 on 2024-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_article_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
