# Generated by Django 5.0.4 on 2025-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_tag_remove_course_school_articletag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_format",
            field=models.CharField(default="markdown", max_length=20),
        ),
    ]
