# Generated by Django 5.0.4 on 2025-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_article_embedding_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="contact",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="marketplace",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
