# Generated by Django 5.0.4 on 2025-07-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_article_contact_article_marketplace_article_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
