# Generated by Django 5.0.4 on 2025-07-15 17:52
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_article_status"),
    ]

    operations = [
        TrigramExtension(),     # creates pg_trgm
        UnaccentExtension(),    # creates unaccent
    ]
