# Generated by Django 5.0.4 on 2025-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0012_remove_notification_group_remove_notification_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="group",
            field=models.IntegerField(choices=[(0, "Comment"), (1, "Like")], default=0),
        ),
    ]
