# Generated by Django 5.0.4 on 2025-06-17 18:44

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_tag_remove_course_school_articletag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="embedding_vector",
            field=models.JSONField(
                blank=True, default=community.models.default_embedding_vectors
            ),
        ),
    ]
