# Generated by Django 5.0.4 on 2025-07-15 18:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_auto_20250715_1752"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "body", config="english"
                ),
                name="article_search_gin",
            ),
        ),
    ]
