# Generated by Django 5.0.4 on 2025-07-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0011_article_article_search_gin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="group",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read",
        ),
    ]
